[variables]
NODE_ENV = "development"

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npx prisma generate --schema=prisma/schema.prisma",
  "npx tsc"
]

[phases.post_build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "NODE_ENV=production node dist/index.js"
