[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npx prisma generate --schema=../../prisma/schema.prisma",
  "npx tsc"
]

[start]
cmd = "node /app/apps/api/dist/index.js"
